const countryLanguages = {
    "Argentina": "Spanish",
    "Australia": "English",
    "Austria": "German",
    "Bahrain": "Arabic",
    "Belgium": "Dutch, French, German",
    "Bolivia": "Spanish, Quechua, Aymara",
    "Brazil": "Portuguese",
    "Bulgaria": "Bulgarian",
    "Canada": "English, French",
    "Chile": "Spanish",
    "China continental": "Mandarin",
    "Colombia": "Spanish",
    "Costa Rica": "Spanish",
    "Croatia": "Croatian",
    "Cyprus": "Greek, Turkish",
    "Czech Republic": "Czech",
    "Denmark": "Danish",
    "Ecuador": "Spanish",
    "El Salvador": "Spanish",
    "Finland": "Finnish, Swedish",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "Guatemala": "Spanish",
    "Honduras": "Spanish",
    "Hong Kong": "Chinese (Cantonese), English",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "India": "Hindi, English, and many regional languages",
    "Indonesia": "Indonesian",
    "Ireland": "Irish, English",
    "Israel": "Hebrew, Arabic",
    "Italy": "Italian",
    "Japan": "Japanese",
    "Korea": "Korean",
    "Kuwait": "Arabic",
    "Lebanon": "Arabic, French",
    "Luxembourg": "Luxembourgish, French, German",
    "Malaysia": "Malay",
    "Malta": "Maltese, English",
    "Mexico": "Spanish",
    "Netherlands": "Dutch",
    "New Zealand": "English, Māori, New Zealand Sign Language",
    "Nicaragua": "Spanish",
    "Norway": "Norwegian",
    "Oman": "Arabic",
    "Panama": "Spanish",
    "Paraguay": "Spanish, Guaraní",
    "Peru": "Spanish, Quechua, Aymara",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Qatar": "Arabic",
    "Romania": "Romanian",
    "Russia": "Russian",
    "Saudi Arabia": "Arabic",
    "Singapore": "English, Mandarin, Malay, Tamil",
    "Slovakia": "Slovak",
    "Slovenia": "Slovenian",
    "South Africa": "11 official languages including Afrikaans, English, Zulu, Xhosa",
    "Sweden": "Swedish",
    "Switzerland": "German, French, Italian, Romansh",
    "Taiwan": "Mandarin",
    "Thailand": "Thai",
    "Turkey": "Turkish",
    "Ukraine": "Ukrainian",
    "United Arab Emirates": "Arabic",
    "United Kingdom": "English",
    "United States": "English",
    "Uruguay": "Spanish"
};

document.getElementById("country").addEventListener("change", function() {
    const selectedCountry = this.value;
    const languageDiv = document.getElementById("language");
    languageDiv.textContent = selectedCountry ? `Language(s): ${countryLanguages[selectedCountry]}` : '';
});